#!/usr/bin/env bash

# Project-specific adapter for the reusable local automation core.
# Copy this file into another repo and change these values first.

AUTOMATION_FRONTEND_DIR_REL="${AUTOMATION_FRONTEND_DIR_REL:-frontend}"
AUTOMATION_BACKEND_DIR_REL="${AUTOMATION_BACKEND_DIR_REL:-backend}"
AUTOMATION_BACKEND_APP_DIR_REL="${AUTOMATION_BACKEND_APP_DIR_REL:-backend/app}"
AUTOMATION_BACKEND_TEST_DIR_REL="${AUTOMATION_BACKEND_TEST_DIR_REL:-backend/tests}"
AUTOMATION_BACKEND_VENV_PYTHON_REL="${AUTOMATION_BACKEND_VENV_PYTHON_REL:-backend/venv/bin/python}"

AUTOMATION_FRONTEND_READY_PATH="${AUTOMATION_FRONTEND_READY_PATH:-/app}"
AUTOMATION_FRONTEND_AUTH_READY_PATH="${AUTOMATION_FRONTEND_AUTH_READY_PATH:-/login}"
AUTOMATION_FRONTEND_USERS_READY_PATH="${AUTOMATION_FRONTEND_USERS_READY_PATH:-/app/users}"
AUTOMATION_FRONTEND_RUNTIME_DETAIL_PATH="${AUTOMATION_FRONTEND_RUNTIME_DETAIL_PATH:-/deployments/smoke-deployment}"

AUTOMATION_FRONTEND_FAST_SMOKES_DEFAULT="${AUTOMATION_FRONTEND_FAST_SMOKES_DEFAULT:-auth ops runtime}"
AUTOMATION_FRONTEND_SMOKE_REGISTRY_DIR="${AUTOMATION_FRONTEND_SMOKE_REGISTRY_DIR:-/tmp/deploymate-frontend-smoke-registry}"
