#!/usr/bin/env node

"use strict";

async function ensureLabel(github, owner, repo, name, color, description) {
  try {
    await github.rest.issues.getLabel({ owner, repo, name });
  } catch (error) {
    if (error.status !== 404) {
      throw error;
    }
    await github.rest.issues.createLabel({
      owner,
      repo,
      name,
      color,
      description,
    });
  }
}

async function listOpenIssues(github, owner, repo, labels) {
  return github.paginate(github.rest.issues.listForRepo, {
    owner,
    repo,
    state: "open",
    labels,
    per_page: 100,
  });
}

async function recentFailureStreak({ github, context, owner, repo, envName, isSelfTest, selfTestAction, threshold }) {
  if (isSelfTest) {
    if (selfTestAction === "update") {
      return threshold;
    }
    return 1;
  }

  const runs = await github.paginate(github.rest.actions.listWorkflowRuns, {
    owner,
    repo,
    workflow_id: "release-secrets-audit.yml",
    branch: context.ref.replace("refs/heads/", ""),
    event: "schedule",
    per_page: 100,
  });

  let streak = 1;
  for (const run of runs) {
    if (run.id === context.runId) {
      continue;
    }

    const jobs = await github.paginate(github.rest.actions.listJobsForWorkflowRun, {
      owner,
      repo,
      run_id: run.id,
      per_page: 100,
    });

    const job = jobs.find((entry) => entry.name === `audit (${envName})`);
    if (!job || job.status !== "completed") {
      continue;
    }

    if (job.conclusion === "failure") {
      streak += 1;
      continue;
    }

    break;
  }

  return streak;
}

async function triageReleaseAuditIncident({ github, context, core, env }) {
  const envName = env.TARGET_ENVIRONMENT;
  const { owner, repo } = context.repo;
  const currentStatus = env.JOB_STATUS;
  const selfTestAction = env.INCIDENT_SELF_TEST_ACTION || "none";
  const isSelfTest = selfTestAction !== "none";
  const title = isSelfTest
    ? `[release-secrets-audit:self-test] ${envName} scheduled audit incident flow`
    : `[release-secrets-audit] ${envName} scheduled audit failing`;
  const assignee = (env.INCIDENT_ASSIGNEE || "").trim();
  const threshold = Math.max(parseInt(env.INCIDENT_FAILURE_THRESHOLD || "3", 10) || 3, 1);
  const incidentLabel = "incident";
  const incidentTestLabel = "incident:test";
  const mediumSeverityLabel = "severity:medium";
  const highSeverityLabel = "severity:high";
  const issues = await listOpenIssues(
    github,
    owner,
    repo,
    isSelfTest ? "ci,release,incident:test" : "ci,release"
  );
  const existing = issues.find((issue) => issue.title === title);

  if (currentStatus === "success") {
    if (!existing) {
      core.notice(`No open incident issue found for ${envName}`);
      return;
    }

    await github.rest.issues.createComment({
      owner,
      repo,
      issue_number: existing.number,
      body: isSelfTest
        ? `Incident self-test resolved successfully.\n\n- Action: \`${selfTestAction}\`\n- Run: ${env.RUN_URL}`
        : `Scheduled audit recovered.\n\n- Run: ${env.RUN_URL}`,
    });

    await github.rest.issues.update({
      owner,
      repo,
      issue_number: existing.number,
      state: "closed",
    });

    core.notice(`Closed incident issue #${existing.number}`);
    return;
  }

  if (currentStatus !== "failure") {
    core.notice(`Skipping incident triage for status ${currentStatus}`);
    return;
  }

  await ensureLabel(github, owner, repo, incidentLabel, "b60205", "Operational incident raised by scheduled audit automation");
  if (isSelfTest) {
    await ensureLabel(github, owner, repo, incidentTestLabel, "1d76db", "Controlled self-test incident generated by audit workflow");
  }
  await ensureLabel(github, owner, repo, mediumSeverityLabel, "fbca04", "Medium-severity operational issue");
  await ensureLabel(github, owner, repo, highSeverityLabel, "d93f0b", "High-severity operational issue");

  const failureStreak = await recentFailureStreak({
    github,
    context,
    owner,
    repo,
    envName,
    isSelfTest,
    selfTestAction,
    threshold,
  });
  const severityLabel = failureStreak >= threshold ? highSeverityLabel : mediumSeverityLabel;
  const severityText = failureStreak >= threshold ? "high" : "medium";
  const labels = isSelfTest
    ? ["ci", "release", incidentLabel, incidentTestLabel, severityLabel]
    : ["ci", "release", incidentLabel, severityLabel];
  const issueBody = [
    isSelfTest ? "## Release secrets audit incident self-test" : "## Release secrets audit incident",
    "",
    isSelfTest
      ? `This is a controlled self-test for the \`${envName}\` scheduled audit incident flow. No production or staging outage is implied.`
      : `The scheduled release secrets audit is failing for \`${envName}\`.`,
    "",
    `- Environment: \`${envName}\``,
    ...(isSelfTest ? [`- Self-test action: \`${selfTestAction}\``] : []),
    `- Severity: \`${severityText}\``,
    `- Consecutive scheduled failures: \`${failureStreak}\``,
    `- Escalation threshold: \`${threshold}\``,
    `- Workflow run: ${env.RUN_URL}`,
    `- Ref: \`${env.REF_NAME}\``,
    `- Commit: \`${String(env.COMMIT_SHA || "").slice(0, 7)}\``,
    "",
    ...(isSelfTest
      ? [
          "Expected operator action:",
          "1. Confirm that the issue title, labels, and comments match the requested self-test action.",
          "2. Re-run the self-test with `update` to verify issue reuse and severity escalation.",
          "3. Re-run the self-test with `resolve` to verify automatic closure.",
        ]
      : [
          "Expected operator action:",
          "1. Open the failed run and read the failing step output.",
          "2. Fix secret drift, SSH connectivity, or target env mismatch.",
          "3. Re-run `Release Secrets Audit` manually to confirm recovery.",
        ]),
  ].join("\n");

  if (existing) {
    await github.rest.issues.update({
      owner,
      repo,
      issue_number: existing.number,
      body: issueBody,
      labels,
      assignees: assignee ? [assignee] : existing.assignees.map((entry) => entry.login),
    });

    await github.rest.issues.createComment({
      owner,
      repo,
      issue_number: existing.number,
      body: [
        isSelfTest ? "Incident self-test updated the existing issue." : "Scheduled audit is still failing.",
        "",
        ...(isSelfTest ? [`- Self-test action: \`${selfTestAction}\``] : []),
        `- Severity: \`${severityText}\``,
        `- Consecutive scheduled failures: \`${failureStreak}\``,
        `- Run: ${env.RUN_URL}`,
        `- Commit: \`${String(env.COMMIT_SHA || "").slice(0, 7)}\``,
      ].join("\n"),
    });

    core.notice(`Updated existing incident issue #${existing.number}`);
    return;
  }

  const created = await github.rest.issues.create({
    owner,
    repo,
    title,
    body: issueBody,
    labels,
    assignees: assignee ? [assignee] : undefined,
  });

  core.notice(`Opened incident issue #${created.data.number}`);
}

module.exports = {
  triageReleaseAuditIncident,
};

if (require.main === module) {
  console.error("This module is intended to be required by github-script or local node tests.");
  process.exit(1);
}
